server:
  port: 7070
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maiksurco/MicroserverBackend.git
          #username:
          #password:
          search-paths: config-data
          default-label: ms-config-server 
  security:
    user:
      name: root
      password: s3cre3t
