server:
  port: 8090
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/maiksurco/MicroserverBackend.git
          search-paths: config-data
          default-label: main
            #username: rickisurco
          #password: a12b68deh6mk89

  security:
    user:
      name: root
      password: s3cre3t
