server:
  port: 8082
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /doc/swagger-ui.html
spring:
  jpa:
    hibernate.ddl-auto: update
    show-sql: true
    generate-ddl: true
  datasource:
    url: jdbc:mysql://localhost:3306/producto?useSSL=false&serverTimezone=UTC
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
